const fs = require('fs');
const path = require('path');

class TfvarsParser {
  /**
   * variables.tf 파일 파싱하여 변수 정의 추출
   * @param {string} projectPath - Terraform 프로젝트 경로
   * @returns {Array} 변수 정의 배열
   */
  parseVariablesFile(projectPath) {
    const variablesFile = path.join(projectPath, 'variables.tf');

    if (!fs.existsSync(variablesFile)) {
      return [];
    }

    const content = fs.readFileSync(variablesFile, 'utf8');
    const variables = [];

    // variable 블록 정규식으로 추출
    const variableRegex = /variable\s+"([^"]+)"\s*\{([^}]+)\}/g;
    let match;

    while ((match = variableRegex.exec(content)) !== null) {
      const varName = match[1];
      const varBlock = match[2];

      const variable = {
        name: varName,
        description: this.extractField(varBlock, 'description'),
        type: this.extractField(varBlock, 'type'),
        default: this.extractField(varBlock, 'default'),
      };

      variables.push(variable);
    }

    return variables;
  }

  /**
   * terraform.tfvars.example 파일 파싱
   * @param {string} projectPath - Terraform 프로젝트 경로
   * @returns {Object} 변수명과 값의 객체
   */
  parseExampleFile(projectPath) {
    const exampleFile = path.join(projectPath, 'terraform.tfvars.example');

    if (!fs.existsSync(exampleFile)) {
      return {};
    }

    const content = fs.readFileSync(exampleFile, 'utf8');
    const variables = {};

    // 각 라인 파싱
    const lines = content.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();

      // 주석이나 빈 줄 건너뛰기
      if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('//')) {
        continue;
      }

      // key = value 형식 파싱
      const match = trimmed.match(/^(\w+)\s*=\s*(.+)$/);
      if (match) {
        const key = match[1];
        let value = match[2].trim();

        // 배열 형식인 경우 그대로 유지
        if (value.startsWith('[') && value.endsWith(']')) {
          variables[key] = value;
        } else {
          // 따옴표 제거 (문자열인 경우만)
          value = value.replace(/^["']|["']$/g, '');
          variables[key] = value;
        }
      }
    }

    return variables;
  }

  /**
   * 변수 정의와 예제 값을 병합
   * @param {string} projectPath - Terraform 프로젝트 경로
   * @returns {Array} UI에 표시할 변수 배열
   */
  getVariablesForUI(projectPath) {
    const definitions = this.parseVariablesFile(projectPath);
    const exampleValues = this.parseExampleFile(projectPath);

    // 정의된 변수와 예제 값 병합
    return definitions.map(def => ({
      name: def.name,
      description: def.description || def.name,
      type: def.type || 'string',
      defaultValue: exampleValues[def.name] || def.default || '',
      value: exampleValues[def.name] || def.default || '',
    }));
  }

  /**
   * terraform.tfvars 파일 생성
   * @param {string} projectPath - Terraform 프로젝트 경로
   * @param {Object} variables - 변수명과 값의 객체
   * @returns {boolean} 성공 여부
   */
  generateTfvarsFile(projectPath, variables) {
    try {
      const tfvarsPath = path.join(projectPath, 'terraform.tfvars');

      let content = '# Auto-generated by Terraform Runner\n';
      content += `# Generated at: ${new Date().toISOString()}\n\n`;

      for (const [key, value] of Object.entries(variables)) {
        // 값이 숫자나 boolean이면 그대로, 문자열이면 따옴표로 감싸기
        const formattedValue = this.formatValue(value);
        content += `${key} = ${formattedValue}\n`;
      }

      fs.writeFileSync(tfvarsPath, content, 'utf8');
      return true;
    } catch (error) {
      console.error('Failed to generate tfvars file:', error);
      return false;
    }
  }

  /**
   * 값을 Terraform 형식으로 포맷
   * @param {any} value - 포맷할 값
   * @returns {string} 포맷된 문자열
   */
  formatValue(value) {
    if (value === null || value === undefined) {
      return '""';
    }

    // 배열인 경우
    if (Array.isArray(value)) {
      const items = value.map(item => this.formatValue(item));
      return `[${items.join(', ')}]`;
    }

    // 문자열이 이미 배열 형식인지 체크 (예: '["a", "b"]' 또는 "[\"a\", \"b\"]")
    if (typeof value === 'string') {
      const trimmed = value.trim();

      // 배열 형식인 경우
      if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
        // 이미 올바른 형식이면 그대로 반환
        return trimmed;
      }

      // 숫자 문자열인 경우
      if (!isNaN(value) && value.trim() !== '') {
        return value.toString();
      }

      // boolean 문자열인 경우
      if (value === 'true' || value === 'false') {
        return value;
      }

      // 일반 문자열인 경우 따옴표로 감싸기
      return `"${value}"`;
    }

    // 숫자인 경우
    if (typeof value === 'number') {
      return value.toString();
    }

    // boolean인 경우
    if (typeof value === 'boolean') {
      return value.toString();
    }

    // 기본: 문자열로 변환
    return `"${value.toString()}"`;
  }

  /**
   * 변수 블록에서 특정 필드 추출
   * @param {string} block - 변수 블록 내용
   * @param {string} field - 추출할 필드명
   * @returns {string|null} 필드 값
   */
  extractField(block, field) {
    const regex = new RegExp(`${field}\\s*=\\s*(.+)`, 'm');
    const match = block.match(regex);

    if (!match) return null;

    let value = match[1].trim();

    // 따옴표 제거
    value = value.replace(/^["']|["']$/g, '');

    return value;
  }

  /**
   * terraform.tfvars.example을 terraform.tfvars로 복사 (빠른 시작용)
   * @param {string} projectPath - Terraform 프로젝트 경로
   * @returns {boolean} 성공 여부
   */
  copyExampleToTfvars(projectPath) {
    try {
      const exampleFile = path.join(projectPath, 'terraform.tfvars.example');
      const tfvarsFile = path.join(projectPath, 'terraform.tfvars');

      if (!fs.existsSync(exampleFile)) {
        return false;
      }

      // 이미 존재하면 덮어쓰지 않음
      if (fs.existsSync(tfvarsFile)) {
        return true;
      }

      fs.copyFileSync(exampleFile, tfvarsFile);
      return true;
    } catch (error) {
      console.error('Failed to copy example file:', error);
      return false;
    }
  }
}

module.exports = new TfvarsParser();

